### ISSUE TITLE
Documentation on Promises is not clear enough OR a better Error message is required

### ISSUE THREAD

**Issue by jonniedarko** [chaijs/chai-http#119]
It may seem obvious to others but I spent a while trying to figure out promises because they are not compatible with `done`

my original test looked like this:
```js
it('it should be able to Create a new User', (done) => {
        chai.request(server)
            .post('/api/users')
            .send({email:'a@b.c', password:'abc123'})
            .then((err, res) => {
                console.log(res);
                res.should.have.status(200);
                res.text.should.be.eq('You must send the username and the password');
              done();
            })
            .catch(done);
      });
```

but I kept getting the error
```
Error: Bad Request
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:626:17)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:795:18)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

When I removed the done, the test passed 

```js
it('it should be able to Create a new User', () => {
        chai.request(server)
            .post('/api/users')
            .send({email:'a@b.c', password:'abc123'})
            .then((err, res) => {
                console.log(res);
                res.should.have.status(200);
                res.text.should.be.eq('User Created');
            })
            .catch((err) => {
                throw err
          });
      });
```

**Comment by jonniedarko** [comment]
This Appears to not be the case, looks like something else is going on
