### ISSUE TITLE
Can't send boolean value in multipart/formdata request

### ISSUE THREAD

**Issue by ablankenship10** [chaijs/chai-http#186]
I have an API that requires a file to be uploaded along with a few other fields of data. One of those fields is a boolean value. When sending this I get this error:

```
Uncaught TypeError: Invalid non-string/buffer chunk
      at validChunk (_stream_writable.js:254:10)
      at Transform.Writable.write (_stream_writable.js:288:21)
      at FormData.ondata (internal/streams/legacy.js:16:26)
      at FormData.CombinedStream.write (node_modules/combined-stream/lib/combined_stream.js:118:8)
      at FormData.CombinedStream._pipeNext (node_modules/combined-stream/lib/combined_stream.js:106:8)
      at FormData.CombinedStream._getNext (node_modules/combined-stream/lib/combined_stream.js:79:10)
      at FormData.CombinedStream._pipeNext (node_modules/combined-stream/lib/combined_stream.js:107:8)
      at FormData.CombinedStream._getNext (node_modules/combined-stream/lib/combined_stream.js:79:10)
      at FormData.CombinedStream._pipeNext (node_modules/combined-stream/lib/combined_stream.js:107:8)
      at FormData.<anonymous> (node_modules/combined-stream/lib/combined_stream.js:91:10)
      at FormData.<anonymous> (node_modules/form-data/lib/form_data.js:248:5)
```

CODE:

```
chai.request(app)
        .post('/v1/upload')
        .set('x-auth-token', DataStore.UserToken)
        .set('Content-Type', 'multipart/formdata')
        .attach('file', FILE_BUFFER, 'file.zip')
        .field('title', 'Some Title')
        .field('image', 'IMAGE_URL')
        .field('language', 'en')
        .field('public', true)
        .end((err, res) => {
          // ...
          done()
        })
```

This does not happen when I send the same `public` field as a 1 or 0 integer, but I think booleans should be supported. This may be functionality of another library (combined-stream?) but figure id post here anyway so i dont choose the wrong one.

**Comment by ablankenship10** [comment]
Actually the integers are converted to strings, so this is still not an adequate work around.

**Comment by kingjerod** [comment]
I have the same problem. As a work around, you can just change your true/false to "true"/"false". Everything sent in a form in the browser is a string anyways.

**Comment by keithamus** [comment]
Hey @ablankenship10 thanks for the issue.

chai-http is really just a chai wrapper around https://github.com/visionmedia/superagent. You should file this issue there - as that will be the repo that needs to implement boolean values.

I'll close this for now; if you file the issue over there and it gets merged feel free to file an issue with us saying to update our version of superagent!

**Comment by vipulrawat** [comment]
Its merged I guess https://github.com/visionmedia/superagent/issues/994
