### ISSUE TITLE
redirectTo() is throwing "TypeError: redirects.indexOf is not a function"

### ISSUE THREAD

**Issue by keith24** [chaijs/chai-http#195]
I _think_ I found a bug!  This is my test: 

``` javascript
// test/auth.js
'use strict'
const request = require('supertest')
const server = require('../server')
const chai = require('chai')
chai.use(
  require('chai-http')
)

// ...

it('Sets a strong password', async () => {

  // Set password
  let set_password_promise = request(server)
    .post(`/settings/password/${passwordless_user.auth.passToken}`)
    .type('form').send({ 'password':TEST_PASSWORD })

  // Expect redirect
  chai.expect(set_password_promise).to.redirectTo('/login?next=/map?new=1') // Line 85

})
```
But it's throwing this error:

> TypeError: redirects.indexOf is not a function
>  at Proxy.<anonymous> (node_modules/chai-http/[lib/http.js:279](https://github.com/chaijs/chai-http/blob/master/lib/http.js#L279):19)
>  at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
>  at Context.it (test/auth.js:85:40)

I edited `lib/http.js` to identify the `typeof redirects` and it came up as a function, not a string.  I can't tell where `redirects` comes from (`this._obj.redirects` is greek to me), so I'm not sure if this is a bug or not.

**Comment by keith24** [comment]
No, it's my fault.  I forgot to `await`:

``` javascript
// Set password
let set_password_promise = await request(server)
  .post(`/settings/password/${passwordless_user.auth.passToken}`)
  .type('form').send({ 'password':TEST_PASSWORD })
```
