### ISSUE TITLE
Occurred 'read ECONNRESET' error when server is listening port only 3000

### ISSUE THREAD

**Issue by HanHyeoksu** [chaijs/chai-http#208]
It is not clear and some weird.
`read ECONNRESET` exception is occurred when I use chai.request() with server that is listening port 3000 but the others port.

Problem code is here:
**./test/test.js**
```js
const chai = require('chai');
chai.use(require('chai-http'));

const Koa = require('koa');
const app = new Koa();

koa.use(ctx => {
  ctx.body = 'hello';
});

const server = koa.listen(3000);

describe('Test', () => {
  it('should get hello', () => {
    chai.request(server)
    .get('/')
    .end((err, res) => {
      if (err) {
        console.error(err);
      }
    });
});
```

**run**
```shell
$ yarn test
```

**result**
```
read ECONNRESET
  at exports._errnoException (util.js:1022:11)
  at TCP.onread (net.js:610:25 
```

**node**: v8.9.4
**yarn**: v1.3.2

If I change the port from 3000 to the other port such as 3001, 1313 then the error is not occurred.
Why does it happen? My environment has some problem or port 3000 is reserved in chai or the others?

I tried to catch exceptions but there's no errors.

```js
process.on('uncaughtException', function (err) {
  console.log(err);
})
```

```js
const server = koa.listen(3000).on('error', err => {
  console.log(err);
});
```

**Comment by austince** [comment]
Port 3000 is definitely not reserved in chai-http, nor should it be on your local computer. I haven't worked with koa in a long time - is starting the server synchronous? Could it be possible that there is a race condition where the server might still be starting when the test is run?
